In [1]:
import numpy as np

In [2]:
list1=[1,2,3,4,5]
arr=np.array(list1)

In [3]:
type(arr)

numpy.ndarray

In [4]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.shape

(5,)

In [9]:
list2=[2,3,4,5,6]
list3=[9,7,6,8,9]
arr=np.array([list1,list2,list3])

In [10]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [11]:
arr.shape

(3, 5)

In [13]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [14]:
arr.shape

(3, 5)

In [18]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[3]

4

In [21]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[:5]

array([1, 2, 3, 4, 5])

In [24]:
arr=np.array([list1,list2,list3])

In [25]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [26]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [27]:
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [28]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [29]:
arr=np.arange(0,13,step=2)

In [30]:
arr

array([ 0,  2,  4,  6,  8, 10, 12])

In [31]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [32]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr1=arr

In [34]:
arr1[3:]=100
print(arr1)

[  1   2   3 100 100 100 100 100 100]


In [35]:
print(arr)

[  1   2   3 100 100 100 100 100 100]


In [36]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [37]:
arr1=arr.copy()

In [38]:
arr1[3:]=200

In [39]:
print(arr)
print(arr1)

[1 2 3 4 5 6 7 8 9]
[  1   2   3 200 200 200 200 200 200]


In [40]:
arr<3

array([ True,  True, False, False, False, False, False, False, False])

In [41]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
arr[arr<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [45]:
arr1=np.arange(0,10).reshape(2,5)
arr2=np.arange(0,10).reshape(2,5)

In [46]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [48]:
np.ones(4)

array([1., 1., 1., 1.])

In [52]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [53]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [55]:
np.random.rand(2,3)

array([[0.0650227 , 0.22079924, 0.93745407],
       [0.79858845, 0.25467365, 0.012988  ]])

In [56]:
np.random.randn(2,3)

array([[-0.24082946,  1.20992423, -0.89663494],
       [ 0.00792628,  0.07176262,  2.87498616]])

In [58]:
np.random.randint(0,100,8)

array([16, 68, 43, 67, 19, 97, 24, 98])

In [59]:
np.random.randint(0,100,(2,3))

array([[97, 95, 64],
       [96, 30, 56]])

In [60]:
np.random.randint(0,100,8).reshape(4,2)

array([[37, 32],
       [28, 21],
       [28, 20],
       [88, 89]])

In [64]:
np.random.random_sample((2,2))

array([[0.71571338, 0.32077583],
       [0.40367584, 0.20737528]])